/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mackittipat.adfly.skipper.ui;

import com.mackittipat.adfly.skipper.core.AdFlySkipper;
import com.mackittipat.adfly.skipper.core.model.TargetUrlModel;
import java.awt.Color;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import javax.swing.text.StyledDocument;

/**
 *
 * @author mac
 */
public class MainWindow extends javax.swing.JFrame {
    
    private AdFlySkipper adFlySkipper;

    /**
     * Creates new form frmMain
     */
    public MainWindow() {
        initComponents();
        adFlySkipper = new AdFlySkipper();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdFlyUrl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTargetUrl = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAdFlyUrl = new javax.swing.JTextPane();
        btnSkip = new javax.swing.JButton();
        btnCheckUrlHealth = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AdFly Skipper");

        lblAdFlyUrl.setText("AdFly URL");
        lblAdFlyUrl.setName(""); // NOI18N

        txtTargetUrl.setName(""); // NOI18N
        jScrollPane1.setViewportView(txtTargetUrl);

        txtAdFlyUrl.setName(""); // NOI18N
        jScrollPane2.setViewportView(txtAdFlyUrl);

        btnSkip.setText("Skip URL");
        btnSkip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkipActionPerformed(evt);
            }
        });

        btnCheckUrlHealth.setText("Check Health");
        btnCheckUrlHealth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckUrlHealthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAdFlyUrl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 435, Short.MAX_VALUE)
                        .addComponent(btnCheckUrlHealth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSkip))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdFlyUrl)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSkip)
                    .addComponent(btnCheckUrlHealth))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSkipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkipActionPerformed
        String[] adFlyUrls = txtAdFlyUrl.getText().split("\n");
        String tartGetUrlResult = "";
        List<TargetUrlModel> targetUrlModelList = 
                adFlySkipper.skipAdFlyUrl(Arrays.asList(adFlyUrls));
        for(TargetUrlModel targetUrlModel : targetUrlModelList) {
            tartGetUrlResult += targetUrlModel.getUrl() + "\n";
        }
        txtTargetUrl.setText(tartGetUrlResult);
        
        
//        DefaultStyledDocument document = new DefaultStyledDocument();
//        txtTargetUrl.setDocument(document);
//        StyleContext context = new StyleContext();
//        // build a style
//        Style style = context.addStyle("test", null);
//        // set some style properties
//        StyleConstants.setForeground(style, Color.BLUE);
//        try {
//            // add some data to the document
//            document.insertString(0, "aasdasdasd\n", style);
//            document.insertString(11, "123123", null);
//        } catch (BadLocationException ex) {
//            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnSkipActionPerformed

    private void btnCheckUrlHealthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckUrlHealthActionPerformed
//        txtTargetUrl.setText("");
        
        DefaultStyledDocument document = new DefaultStyledDocument();
        StyleContext context = new StyleContext();

        Style styleBlue = context.addStyle("styleBlue", null);
        StyleConstants.setForeground(styleBlue, Color.BLUE);
        
        Style styleRed = context.addStyle("styleRed", null);
        StyleConstants.setForeground(styleRed, Color.RED);       
        
        String txtTargetUrlContent = "";
        
        System.out.println(txtTargetUrl.getText());
        String[] targetUrls = txtTargetUrl.getText().split("\n");
        for(String targetUrl : targetUrls) {
            System.out.println(">>> " + targetUrl);
            if(adFlySkipper.retrieveRequestStatus(targetUrl)) {
                try {
                    document.insertString(txtTargetUrlContent.length(), targetUrl + "\n", styleBlue);
                    txtTargetUrlContent += targetUrl + "\n";
                } catch (BadLocationException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    document.insertString(txtTargetUrlContent.length(), targetUrl + "\n", styleRed);
                    txtTargetUrlContent += targetUrl + "\n";
                } catch (BadLocationException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        txtTargetUrl.setDocument(document);
        
//        DefaultStyledDocument document = new DefaultStyledDocument();
//        StyleContext context = new StyleContext();
//        // build a style
//        Style style = context.addStyle("test", null);
//        // set some style properties
//        StyleConstants.setForeground(style, Color.BLUE);
//        try {
//            // add some data to the document
//            document.
//            document.insertString(0, "aasdasdasd\n", style);
//            document.insertString(11, "123123", null);
//        } catch (BadLocationException ex) {
//            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_btnCheckUrlHealthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckUrlHealth;
    private javax.swing.JButton btnSkip;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAdFlyUrl;
    private javax.swing.JTextPane txtAdFlyUrl;
    private javax.swing.JTextPane txtTargetUrl;
    // End of variables declaration//GEN-END:variables
}
